In [1]:
import pandas as pd

In [2]:
import glob

In [3]:
path = glob.glob('data/*.csv')
path

['data\\강원도_반려동물 동반관광 정보_20211221.csv',
 'data\\반려동물등록현황.csv',
 'data\\서울시 동물판매업 인허가 정보.csv']

In [4]:
#모든 행 
pd.set_option('display.max_columns', None)
#모든 열
pd.set_option('display.max_rows', None)

 #### `강원도_반려동물 동반관광 정보.csv`

In [8]:
data_1 = pd.read_csv(path[0], encoding = 'cp949')
data_1.sample(5)

,업체구분,업체명,지번 주소,도로명 주소,위도,경도,연락처
324,동물병원,도그빌동물병원,강원도 강릉시 교동 225-12,강원도 강릉시 명륜로 23-1,37.762138,128.895942,033-645-2289
422,식음료,흰다정,강원도 속초시 동명동 450-238,강원도 속초시 수복로 248,38.209309,128.591344,070-8830-9322
451,관광지,파로호 하트섬,강원도 화천군 간동면 도송리 481,NaN,38.064636,127.795216,NaN
316,관광지,송정해변,강원도 강릉시 송정동 1,강원도 강릉시 송정길30번안길 20-3,37.776796,128.937200,033-640-5422
359,관광지,설악해수욕장,강원도 양양군 강현면 전진2리,강원도 양양군 강현면 동해대로 3254,38.124207,128.629965,033-670-2518

 #### `반려동물등록현황.csv`

In [11]:
data_2 = pd.read_csv(path[1], encoding = 'cp949')
data_2.sample(5)

,시군명,읍면동명,등록동물수(마리),(등록주체)시군구등록,(등록주체)대행업체등록,(등록주체)기타,(RFID종류)내장형,(RFID종류)외장형,(RFID종류)인식표,등록품종수,등록소유자수,동물소유자당등록동물수,해당동의등록대행업체수,데이터기준일자
639,포천시,선단동,858,10.0,847.0,1.0,623,129,106,54.0,532.0,1.61,1.0,2021-08-24
48,고양시,탄현동,3664,24.0,3640.0,0.0,2312,1067,285,92.0,2861.0,1.28,NaN,2022-06-03
438,여주시,신진동,11,6.0,5.0,0.0,4,1,6,8.0,9.0,1.22,0.0,2021-08-31
537,이천시,고담동,78,9.0,69.0,0.0,33,35,10,27.0,60.0,1.30,0.0,2021-07-29
362,안성시,숭인동,115,8.0,107.0,0.0,51,50,14,24.0,90.0,1.28,NaN,2021-09-06

#### `서울시 동물판매업 인허가 정보.csv`

In [10]:
data_3 = pd.read_csv(path[2], encoding = 'cp949')
data_3.sample(5)

,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,휴업시작일자,휴업종료일자,재개업일자,전화번호,소재지면적,소재지우편번호,지번주소,도로명주소,도로명우편번호,사업장명,최종수정일자,데이터갱신구분,데이터갱신일자,업태구분명,좌표정보(X),좌표정보(Y),축산업무구분명,축산물가공업구분명,축산일련번호,권리주체일련번호,총인원
2663,3180000,318000003720200002,20200306,NaN,4,취소/말소/만료/정지/중지,4,말소,20220526.0,NaN,NaN,NaN,02-832-4588,0.0,NaN,서울특별시 영등포구 신길동 ***-*번지 성락빌딩,서울특별시 영등포구 가마산로 *** 성락빌딩 *층 (신길동),7404.0,휴먼플러스(개밥주는고양이),20200306165129,I,2021-12-04 22:07:00.0,NaN,191180.245266,444543.273189,NaN,NaN,NaN,NaN,NaN
7538,3060000,306000003720150003,20150713,NaN,4,취소/말소/만료/정지/중지,4,말소,20220526.0,NaN,NaN,NaN,NaN,0.0,NaN,서울특별시 중랑구 묵동 ***-** *층,서울특별시 중랑구 동일로 *** *층 (묵동),2046.0,포유독 강아지 중랑점,20220120145351,U,2021-12-04 22:07:00.0,NaN,206893.453885,456018.381746,NaN,NaN,NaN,NaN,NaN
7033,3200000,320000004520180001,20180109,NaN,3,폐업,2,폐업,20211102.0,NaN,NaN,NaN,NaN,0.0,NaN,서울특별시 관악구 봉천동 ***-*,서울특별시 관악구 남부순환로 **** *층 ***호 (봉천동),8758.0,피에스타,20220428181044,I,2021-12-04 22:07:00.0,NaN,195283.266814,442213.222789,NaN,NaN,NaN,NaN,NaN
1456,3210000,321000004820210006,20210804,NaN,1,영업/정상,0,정상,NaN,NaN,NaN,NaN,02-535-7942,0.0,NaN,서울특별시 서초구 서초동 ****-** 세계빌딩,서울특별시 서초구 서초대로**길 ** 세계빌딩 B*층 (서초동),6615.0,(주)스타몽,20220428181058,I,2021-12-04 22:07:00.0,NaN,202216.105553,444042.746664,NaN,NaN,NaN,NaN,NaN
6273,3240000,324000003720180032,20180710,NaN,4,취소/말소/만료/정지/중지,4,말소,20220526.0,NaN,NaN,NaN,NaN,0.0,NaN,서울특별시 강동구 고덕동 ***번지 래미안힐스테이트고덕 상가*층 ***호,서울특별시 강동구 아리수로**길 ** (고덕동 래미안힐스테이트고덕),5229.0,고래힐 동물병원,20180710110958,I,2021-12-04 22:07:00.0,NaN,212926.089913,450751.524332,NaN,NaN,NaN,NaN,NaN

In [12]:
path_1 = glob.glob('data/*.xls')
path_1

['data\\애견동반카페 키워드.xls']

#### `1년간 애견동반카페 키워드.csv`

In [22]:
data_4 = pd.read_excel(path_1[0])
data_4.iloc[7:, :].sample(5)

                      기간 2021-06-15 ~ 2022-06-15
233  2022-01-27 00:00:00                      10
162  2021-11-17 00:00:00                       0
289  2022-03-24 00:00:00                      14
382                   연령                  애견동반카페
306  2022-04-10 00:00:00                      27